apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.6
            name: cdf-start-pipeline
            resources: { }
            script: |
              #!/usr/bin/env sh
              source /workspace/source/.jx/variables.sh
              export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
              cdf pipeline started --type module --module cd-flow-cli --id $VERSION || true
        - name: release-binary
          resources: {}
        - name: build-and-push-image
          resources: {}
        - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.6
          name: cdf-artifact-built
          resources: { }
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh
            export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
            cdf artifact built --module cd-flow-cli --pipelineId $VERSION --id cd-flow-cli || true
#        - name: chart-docs
#          resources: {}
        - name: changelog
          resources: {}
        - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.6
          name: cdf-release-and-finish-pipeline
          resources: { }
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh
            export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
            cdf artifact released --module cd-flow-cli --pipelineId $VERSION --id cd-flow-cli
            cdf pipeline finished --type module --module cd-flow-cli --id $VERSION || true
#        - name: release-chart
#          resources: {}
#        - name: upload-binaries
#          resources: {}
#        - name: promote-release
#          resources: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
